export const portfolioData = {
  en: {
    "about": "Senior Full-Stack Engineer with over 9 years of experience designing and engineering large-scale interactive applications used by more than 100 million users worldwide. My expertise spans high-ownership products, AI-driven systems, multimodal interaction, and full-stack architecture across web, mobile, and blockchain platforms. I have led technical teams, authored a book on AI model training, and developed advanced prototypes integrating human–AI interaction and machine learning models. (No visa sponsorship needed)",

    "experience": "💼 Professional Experience:\n\nDuoduo Company (for Gate.io), Beijing, China — Flutter & FullStack Engineer (Jan. 2023 - Dec. 2023)\n• Responsible for cryptocurrency wallets and blockchain transactions on Bitcoin and Ethereum.\n• Designed and integrated new blockchain protocols for over 23 million users.\n\nYidian Inc., Beijing, China — TechLead & Senior FullStack (Sept. 2020 - Dec. 2022)\n• Led NFT and Token market transactions across multiple blockchains.\n• Developed the Yidian Breaking News app serving 100 million monthly active users.\n\nTelabytes Startup, Beijing, China — Co-founder & Senior FullStack (Sept. 2017 - Aug. 2020)\n• Founded and managed the technical team, overseeing recruitment and product design.\n• Built an AI-based foreign language learning app (Yooul), growing DAU to 500K within six months.\n\nQihoo 360 Inc., Beijing, China — iOS Engineer (Sept. 2014 - Aug. 2017)\n• Designed and implemented Red Packet features and the IM protocol.\n• Developed a bridge between native and web modules for the app with 20M DAU.",

    "education": "🎓 Education:\n\nNorthern Arizona University, USA — Master's Degree\n (Feb. 2024 - May 2025)\n• Computer Information Technology (GPA 4.0)\nDissertation: Burn-After-Use for Preventing Data Leakage through a Secure Multi-Tenant Architecture in Enterprise LLM - published on <a href='https://arxiv.org/abs/2601.06627'style='color:blue;'>arXiv</a> and IEEE Access \n\nJilin University, China — Bachelor's Degree\n (Sept. 2011 - July 2015)\n• Business Administration",

    "skills": "🚀 Technical Skills:\n\nMobile Development: Flutter, Swift, Objective-C, Dart, SwiftUI, UIKit, Firebase, Apple Augmented Reality, In-App Purchases\nFullStack Development: NodeJS, Python, JavaScript/TypeScript, Stripe, ExpressJS, NextJS, ReactJS, PostgreSQL, MySQL, Golang, Ethereum, Bitcoin Script, Truffle, A/B Testing, TDD, LLM, RAG, RAGAs, LangChain, LangGraph, LlamaIndex, LLM APIs, ClaudeCode, Copilot, OpenAI Codex.\nCloud & DevOps: AWS (EC2/ CloudFront/ S3/ RDS/ Lambda/ Edge/ APIGateway/ Amplify/ SNS), GCP, Docker, Serverless, Prometheus, Grafana, gRPC, Ethereum Solidity EVM, Distributed Ledger, CI/CD, CDN, Jira, Git\nOther: App Store, Google Play Store, In-App Purchases\n\nLanguages: English (Professional), German (A2), French (B1), Chinese (Native)\n\nSoft Skills: Technical Leadership, Team Management, Problem Solving, Cross-functional Communication, Agile Development",

    "projects": "🎨 Featured Projects:\n\nToutCas AI — Privacy AI Agent Browser [<a href='https://github.com/VictorZhang2014/toutcas' style='color: blue;'>Project</a>] \n• Conceptualized and concretized the AI Agent browser across multiple OS platforms, multi-tenant isolation, data minimization and burn after use once finishing the LLM reasoning\n• Developed by RAG-as-a-base architecture, LangGraph and LlamaIndex as the vector indexing, storage and retrieving engine, files to text by MarkItDown, text-to-vector by text-embedding-3 in PGVectorStore\n• Tech stack: Python/TypeScript, Flutter, LangChain, PostgreSQL Vector, OpenAI/HuggingFace/Gemini\n\nGate.io App — Cryptocurrency Exchange | [<a href='https://www.gate.io/' style='color:blue;'>Web</a>] [<a href='https://apps.apple.com/us/app/gate-trade-btc-eth/id1294998195' style='color:blue;'>iOS</a>] [<a href='https://play.google.com/store/apps/details?id=com.gateio.gateio&hl=en' style='color:blue;'>Android</a>]\n• Designed and implemented a bridge between Rune Protocol and Gate.io Bitcoin Wallet.\n• Built zero-gas cross-chain transactions and optimized mnemonics with FIDO 2.\n• Tech stack: Flutter, Swift, NodeJS, ReactJS, Docker, AWS, Ethereum.\n\nBandee App — Web3 Social Platform | [<a href='https://apps.apple.com/ph/app/bondee/id6443947003' style='color:blue;'>iOS</a>] [<a href='https://play.google.com/store/apps/details?id=com.metadream.bondee&hl=en&gl=US' style='color:blue;'>Android</a>]\n• Developed smart contracts for NFT and token markets (ERC20, ERC721, ERC1155, OpenSea, UniSwap).\n• Managed Web3 development team and automated deployment pipeline.\n• Tech stack: Solidity, Ethereum, NodeJS, PostgreSQL, NextJS, Flutter, Firebase, Prometheus.\n\nYidian News App — News Application | [<a href='https://www.yidianzixun.com' style='color:blue;'>Web</a>] [<a href='https://apps.apple.com/cn/app/一点资讯-实时新闻热点全覆盖/id976039116' style='color:blue;'>iOS</a>] [<a href='https://sj.qq.com/appdetail/com.hipu.yidian?ckey=CK1283542019108&from_wxz=1' style='color:blue;'>Android</a>]\n• Optimized large image and video downloads, reducing iOS app size by 30% via dynamic loading.\n• Collaborated with product managers for new feature definition and delivery.\n• Tech stack: Objective-C, Swift, SQLite, Flutter, CocoaPods, CI/CD.\n\nLanXin App — Enterprise Instant Messaging | [<a href='https://apps.apple.com/cn/app/蓝信-全场景智能化安全协同平台/id1463938727' style='color:blue;'>iOS</a>] [<a href='https://sj.qq.com/appdetail/com.lite.lanxin' style='color:blue;'>Android</a>]\n• Developed QR code/barcode scanner with AVFoundation and improved JS interoperability via JavaScriptCore.\n• Designed and implemented Red Packet system, optimized message delivery with SQLCipher.\n• Tech stack: Objective-C, SQLCipher, SQLite, CI/CD, SocketIO.",

    "contact": "📧 Contact:\n\n📍 14059 Berlin, Germany\n📮 victorzhangq@gmail.com\n\nLinkedIn: <a href='https://linkedin.com/in/qiang-zhang-36662792' style='color: blue;'>linkedin.com/in/qiang-zhang-36662792</a>\nGitHub: <a href='https://github.com/VictorZhang2014' style='color: blue;'>github.com/VictorZhang2014</a>\nPortfolio: <a href='https://qiangzhang.xyz' style='color: blue;'>qiangzhang.xyz</a> and <a href='https://qiangzhang.xyz/fullstack.html' style='color: blue;'>works show</a>\n\nAchievements:\n• Published book: 'Best Practices for Training AI Models in 21 Projects' (JD.com, 2019)\n• Tech Blog with over 1.6 millions of reads at <a href='https://zhangqiang.blog.csdn.net' style='color: blue;'>zhangqiang.blog.csdn.net</a>\n\nAlways open to discussing new opportunities, collaborations, or innovative projects. Typically replies within 24 hours!"
  },
  de: {
    "about": "Senior Full-Stack-Entwickler mit mehr als 9 Jahren Erfahrung in der Konzeption und Entwicklung groß angelegter interaktiver Anwendungen, die weltweit von über 100 Millionen Nutzern verwendet werden. Meine Expertise umfasst Produkte mit hoher Besitzquote, KI-gestützte Systeme, multimodale Interaktion sowie Full-Stack-Architekturen für Web-, Mobile- und Blockchain-Plattformen. Ich habe technische Teams geleitet, ein Buch über das Training von KI-Modellen verfasst und fortgeschrittene Prototypen entwickelt, die Mensch-KI-Interaktion und Machine-Learning-Modelle integrieren. (Kein Visumsponsoring erforderlich)",

    "experience": "💼 Berufserfahrung:\n\nDuoduo Company (für Gate.io), Peking, China — Flutter- & Full-Stack-Entwickler (Jan. 2023 - Dez. 2023)\n• Verantwortlich für Kryptowallets und Blockchain-Transaktionen auf Bitcoin und Ethereum.\n• Entwarf und integrierte neue Blockchain-Protokolle für über 23 Millionen Nutzer.\n\nYidian Inc., Peking, China — Tech Lead & Senior Full-Stack (Sept. 2020 - Dez. 2022)\n• Leitete NFT- und Token-Marktplatztransaktionen über mehrere Blockchains hinweg.\n• Entwickelte die Breaking-News-App von Yidian für 100 Millionen monatlich aktive Nutzer.\n\nTelabytes Startup, Peking, China — Mitgründer & Senior Full-Stack (Sept. 2017 - Aug. 2020)\n• Gründete und leitete das technische Team, einschließlich Recruiting und Produktdesign.\n• Entwickelte eine KI-basierte Fremdsprachen-Lern-App (Yooul), die innerhalb von sechs Monaten auf 500.000 tägliche aktive Nutzer anwuchs.\n\nQihoo 360 Inc., Peking, China — iOS-Entwickler (Sept. 2014 - Aug. 2017)\n• Konzipierte und implementierte Red-Packet-Funktionen sowie das IM-Protokoll.\n• Entwickelte eine Brücke zwischen nativen und Web-Modulen für die App mit 20 Millionen täglichen aktiven Nutzern.",

    "education": "🎓 Ausbildung:\n\nNorthern Arizona University, USA — Masterabschluss\n (Feb. 2024 - Mai 2025)\n• Computer Information Technology (GPA 4,0)\nDissertation: Burn-After-Use zur Verhinderung von Datenlecks durch eine sichere Multi-Tenant-Architektur in Enterprise-LLMs - veröffentlicht auf <a href='https://arxiv.org/abs/2601.06627' style='color:blue;'>arXiv</a> und in IEEE Access \n\nJilin University, China — Bachelorabschluss\n (Sept. 2011 - Juli 2015)\n• Betriebswirtschaftslehre",

    "skills": "🚀 Technische Fähigkeiten:\n\nMobile Entwicklung: Flutter, Swift, Objective-C, Dart, SwiftUI, UIKit, Firebase, Apple Augmented Reality, In-App-Käufe\nFull-Stack-Entwicklung: NodeJS, Python, JavaScript/TypeScript, Stripe, ExpressJS, NextJS, ReactJS, PostgreSQL, MySQL, Golang, Ethereum, Bitcoin Script, Truffle, A/B-Testing, TDD, LLM, RAG, RAGAs, LangChain, LangGraph, LlamaIndex, LLM-APIs, ClaudeCode, Copilot, OpenAI Codex.\nCloud & DevOps: AWS (EC2/ CloudFront/ S3/ RDS/ Lambda/ Edge/ APIGateway/ Amplify/ SNS), GCP, Docker, Serverless, Prometheus, Grafana, gRPC, Ethereum Solidity EVM, Distributed Ledger, CI/CD, CDN, Jira, Git\nSonstiges: App Store, Google Play Store, In-App-Käufe\n\nSprachen: Englisch (Beruflich), Deutschsprache (A2), Chinesisch (Muttersprache)\n\nSoft Skills: Technische Führung, Teammanagement, Problemlösung, funktionsübergreifende Kommunikation, agile Entwicklung",

    "projects": "🎨 Ausgewählte Projekte:\n\nToutCas AI — Datenschutzorientierter KI-Agenten-Browser [<a href='https://github.com/VictorZhang2014/toutcas' style='color: blue;'>Projekt</a>] \n• Konzipierte und realisierte den KI-Agenten-Browser für mehrere Betriebssystemplattformen, mit Multi-Tenant-Isolation, Datenminimierung und Burn-after-Use nach Abschluss der LLM-Inferenz.\n• Entwickelt auf Basis einer RAG-as-a-base-Architektur, mit LangGraph und LlamaIndex als Engine für Vektorindexierung, Speicherung und Abruf, Dateikonvertierung zu Text mit MarkItDown sowie Text-zu-Vektor mit text-embedding-3 in PGVectorStore.\n• Tech-Stack: Python/TypeScript, Flutter, LangChain, PostgreSQL Vector, OpenAI/HuggingFace/Gemini\n\nGate.io App — Kryptowährungsbörse | [<a href='https://www.gate.io/' style='color:blue;'>Web</a>] [<a href='https://apps.apple.com/us/app/gate-trade-btc-eth/id1294998195' style='color:blue;'>iOS</a>] [<a href='https://play.google.com/store/apps/details?id=com.gateio.gateio&hl=en' style='color:blue;'>Android</a>]\n• Entwarf und implementierte eine Brücke zwischen dem Rune-Protokoll und der Gate.io-Bitcoin-Wallet.\n• Entwickelte Zero-Gas-Cross-Chain-Transaktionen und optimierte Mnemonics mit FIDO 2.\n• Tech-Stack: Flutter, Swift, NodeJS, ReactJS, Docker, AWS, Ethereum.\n\nBandee App — Web3-Sozialplattform | [<a href='https://apps.apple.com/ph/app/bondee/id6443947003' style='color:blue;'>iOS</a>] [<a href='https://play.google.com/store/apps/details?id=com.metadream.bondee&hl=en&gl=US' style='color:blue;'>Android</a>]\n• Entwickelte Smart Contracts für NFT- und Token-Märkte (ERC20, ERC721, ERC1155, OpenSea, UniSwap).\n• Leitete das Web3-Entwicklungsteam und automatisierte die Deployment-Pipeline.\n• Tech-Stack: Solidity, Ethereum, NodeJS, PostgreSQL, NextJS, Flutter, Firebase, Prometheus.\n\nYidian News App — Nachrichten-App | [<a href='https://www.yidianzixun.com' style='color:blue;'>Web</a>] [<a href='https://apps.apple.com/cn/app/一点资讯-实时新闻热点全覆盖/id976039116' style='color:blue;'>iOS</a>] [<a href='https://sj.qq.com/appdetail/com.hipu.yidian?ckey=CK1283542019108&from_wxz=1' style='color:blue;'>Android</a>]\n• Optimierte große Bild- und Video-Downloads und reduzierte die Größe der iOS-App durch dynamisches Laden um 30 %.\n• Arbeitete mit Produktmanagern bei der Definition und Umsetzung neuer Funktionen zusammen.\n• Tech-Stack: Objective-C, Swift, SQLite, Flutter, CocoaPods, CI/CD.\n\nLanXin App — Unternehmens-Messaging | [<a href='https://apps.apple.com/cn/app/蓝信-全场景智能化安全协同平台/id1463938727' style='color:blue;'>iOS</a>] [<a href='https://sj.qq.com/appdetail/com.lite.lanxin' style='color:blue;'>Android</a>]\n• Entwickelte einen QR-Code-/Barcode-Scanner mit AVFoundation und verbesserte die JS-Interoperabilität mit JavaScriptCore.\n• Konzipierte und implementierte ein Red-Packet-System und optimierte die Nachrichtenübermittlung mit SQLCipher.\n• Tech-Stack: Objective-C, SQLCipher, SQLite, CI/CD, SocketIO.",

    "contact": "📧 Kontakt:\n\n📍 14059 Berlin, Deutschland\n📮 victorzhangq@gmail.com\n\nLinkedIn: <a href='https://linkedin.com/in/qiang-zhang-36662792' style='color: blue;'>linkedin.com/in/qiang-zhang-36662792</a>\nGitHub: <a href='https://github.com/VictorZhang2014' style='color: blue;'>github.com/VictorZhang2014</a>\nPortfolio: <a href='https://qiangzhang.xyz' style='color: blue;'>qiangzhang.xyz</a> und <a href='https://qiangzhang.xyz/fullstack.html' style='color: blue;'>Projektübersicht</a>\n\nErfolge:\n• Veröffentlichtes Buch: 'Best Practices for Training AI Models in 21 Projects' (JD.com, 2019)\n• Tech-Blog mit über 1,6 Millionen Aufrufen auf <a href='https://zhangqiang.blog.csdn.net' style='color: blue;'>zhangqiang.blog.csdn.net</a>\n\nIch bin immer offen für Gespräche über neue Möglichkeiten, Kooperationen oder innovative Projekte. In der Regel antworte ich innerhalb von 24 Stunden."
  },
  fr: {
    "about": "Développeur Full-Stack senior, fort de plus de 9 ans d'expérience dans la conception et l'ingénierie d'applications interactives à grande échelle, utilisées par plus de 100 millions d'utilisateurs dans le monde. Mon expertise couvre les produits à forte propriété, les systèmes pilotés par l'intelligence artificielle, l'interaction multimodale et l'architecture full-stack sur les plateformes web, mobiles et blockchain. J'ai dirigé des équipes techniques, publié un ouvrage sur l'entraînement des modèles d'IA et conçu des prototypes avancés intégrant l'interaction homme-IA et modèle de l'apprentissage machine. (Pas besoin de parrainage de visa)",

    "experience": "💼 Expérience Professionnelle :\n\nDuoduo Company (for Gate.io), Pékin, Chine — Ingénieur Flutter & FullStack (Janv. 2023 - Déc. 2023)\n• Responsable des portefeuilles cryptographiques, des transactions Bitcoin et Ethereum, et de l'intégration de nouveaux protocoles (23 M d'utilisateurs)\n\nYidian Inc., Pékin, Chine — TechLead & FullStack Senior (Sept. 2020 - Déc. 2022)\n• Direction des transactions NFT et Token sur plusieurs blockchains\n• Responsable du développement de l'application d'actualités Yidian Breaking News (100 M MAU)\n\nTelabytes Startup, Pékin, Chine — Co-fondateur & FullStack Senior (Sept. 2017 - Août 2020)\n• Création et direction d'une équipe technique\n• Développement d'une application d'apprentissage des langues basée sur l'IA (Yooul) avec une croissance du DAU à 500 K en 6 mois\n\nQihoo 360 Inc., Pékin, Chine — Ingénieur iOS (Sept. 2014 - Août 2017)\n• Conception et implémentation de fonctionnalités Red Packet et protocole IM\n• Développement d'un pont entre modules natifs et Web (20 M DAU)",

    "education": "🎓 Formation :\n\nUniversité du Nord de l'Arizona, États-Unis — Master\n (Févr. 2024 - Mai 2025)\n• Technologies de l'information informatique\nThèse : Se brûler des données après utilisation pour prévenir les fuites de données grâce à une architecture mutualisée sécurisée dans une entreprise de LLM - publié sur <a href='https://arxiv.org/abs/2601.06627'style='color:blue;'>arXiv</a> et IEEE Access\n\nAlliance Française de Toulouse, France — Apprentissage du français\n (Sept. 2024 - Oct. 2024)\n\nUniversité de Jilin, Chine — Licence\n (Sept. 2011 - Juil. 2015)\n• Administration des affaires",

    "skills": "🚀 Compétences Techniques :\n\nMobile : Flutter, Swift, Objective-C, Dart, SwiftUI, UIKit, Firebase, Apple Augmented Reality, In-App Purchases\nFullStack : NodeJS, Python, JavaScript/TypeScript, ExpressJS, NextJS, ReactJS, Stripe, PostgreSQL, MySQL, Golang, Ethereum, Bitcoin Script, Truffle, A/B Testing, TDD, LLM, RAG, RAGAs, LangChain, LangGraph, LlamaIndex, LLM APIs, ClaudeCode, Copilot, OpenAI Codex.\nCloud & DevOps : AWS (EC2/ CloudFront/ S3/ RDS/ Lambda/ Edge/ APIGateway/ Amplify/ SNS), GCP, Docker, Serverless, Prometheus, Grafana, gRPC, Ethereum Solidity EVM, Distributed Ledger, CI/CD, CDN, Jira, Git\nAutres : App Store, Google Play Store, Achats intégrés\n\nLangues : Anglais (professionnel), Français (intermédiaire), Chinois (natif)\n\nSoft Skills : Leadership technique, Gestion d'équipe, Communication interculturelle, Résolution de problèmes",

    "projects": "🎨 Projets en vedette :\n\nToutCas AI — Navigateur privé de l'IA d'agent [<a href='https://github.com/VictorZhang2014/toutcas' style='color: blue;'>Project</a>] \n• Conception et réalisation d’un navigateur d’agent IA multi-plateforme, isolation multi-tenant, minimisation des données et suppression des données après utilisation suite au raisonnement LLM (mécanisme BAU)\n• Développé avec une architecture de base RAG, LangGraph et LlamaIndex comme moteur d'indexation, de stockage et de récupération vectoriels, conversion de fichiers en texte avec MarkItDown, conversion de texte en vecteur avec text-embedding-3 dans PGVectorStore\n• Tech stack: Python/TypeScript, Flutter, LangChain, PostgreSQL Vector, OpenAI/HuggingFace/Gemini\n\nYidian News App — Application d'actualités (<a href='https://www.yidianzixun.com' style='color:blue;'>Web</a> / <a href='https://apps.apple.com/cn/app/一点资讯-实时新闻热点全覆盖/id976039116' style='color:blue;'>iOS</a> / <a href='https://sj.qq.com/appdetail/com.hipu.yidian?ckey=CK1283542019108&from_wxz=1' style='color:blue;'>Android</a>)\n• Réduction de 30% de la taille de l'application iOS via chargement dynamique des ressources\n• Stack : Objective-C, Swift, SQLite, Flutter, CI/CD\n\nLanXin App — Messagerie d'entreprise (<a href='https://apps.apple.com/cn/app/蓝信-全场景智能化安全协同平台/id1463938727' style='color:blue;'>iOS</a> / <a href='https://sj.qq.com/appdetail/com.lite.lanxin' style='color:blue;'>Android</a>)\n• Développement du scanner QR/barcode et du système Red Packets\n• Stack : Objective-C, SQLCipher, SQLite, SocketIO\n\nGate.io App — Échange de crypto-monnaies (<a href='https://www.gate.io/' style='color:blue;'>Web</a> / <a href='https://apps.apple.com/us/app/gate-trade-btc-eth/id1294998195' style='color:blue;'>iOS</a> / <a href='https://play.google.com/store/apps/details?id=com.gateio.gateio&hl=en' style='color:blue;'>Android</a>)\n• Implémentation du pont entre Rune Protocol et Bitcoin Wallet\n• Stack : Flutter, Swift, NodeJS, ReactJS, Docker, AWS, Ethereum\n\nBandee App — Plateforme sociale Web3 (<a href='https://apps.apple.com/ph/app/bondee/id6443947003' style='color:blue;'>iOS</a> / <a href='https://play.google.com/store/apps/details?id=com.metadream.bondee&hl=en&gl=US' style='color:blue;'>Android</a>)\n• Développement de smart contracts pour NFT et tokens ERC20/721/1155\n• Stack : Solidity, Ethereum, NodeJS, PostgreSQL, NextJS, Flutter, Firebase, Prometheus",

    "contact": "📧 Mes informations :\n\n📍 75014 Paris, France\n📮 francoiszhangq@gmail.com\n\nLinkedIn : <a href='https://www.linkedin.com/in/fran%C3%A7oiszhang/' style='color: blue;'>linkedin.com/in/françoiszhang/</a>\nGitHub : <a href='https://github.com/VictorZhang2014' style='color: blue;'>github.com/VictorZhang2014</a>\nPortfolio : <a href='https://qiangzhang.xyz' style='color: blue;'>qiangzhang.xyz</a> et <a href='https://qiangzhang.xyz/fullstack.html' style='color: blue;'>works show</a>\n\nBlog sur ta technologique avec plus de 1,6 million de lectures sur <a href='https://zhangqiang.blog.csdn.net' style='color: blue;'>zhangqiang.blog.csdn.net</a>\n\nJe suis toujours ouvert à discuter de nouvelles opportunités ou collaborations. Réponse sous 24h !"
  }
}
